# Generated by Django 4.2.1 on 2023-05-18 10:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name', max_length=50)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Item weight', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('is_fragile', models.BooleanField(default=False, help_text='Is item fragile?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Item creation date')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
