# Generated by Django 4.2.1 on 2023-05-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Shipment status', max_length=10)),
                ('address', models.CharField(help_text='Destination address', max_length=150)),
                ('comment', models.CharField(blank=True, help_text='Additional information', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Shipment creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Shipment last update date')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Shipment sent date', null=True)),
                ('city', models.ForeignKey(help_text='Destination city', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.city')),
                ('items', models.ManyToManyField(help_text='Items delivered in this shipment', related_name='shipments', to='catalog.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(help_text='Country where the city is located', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shipments.country'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_city'),
        ),
    ]
